apiVersion: v1
kind: Service
metadata:
  labels:
    app: tng-crs-authentication
  name: tng-crs-authentication
spec:
  ports:
  - port: 9005
    protocol: TCP
    targetPort: 9005
  selector:
    app: tng-crs-authentication
    tier: backend  